import { Post as IPost } from 'api/endpoints/blog';

const mockPosts: IPost[] = [
  {
    id: 1,
    image: "http://cdn.motorpage.ru/Photos/300/14F3.jpg",
    text: "Some Ferrari",
    date: "2021-10-08",
    lessonNum: 49,
    title: "Ferrari",
    author: 123,
    like: 10, 
    dislike: 0,
    isFavorite: false, 
  },
  {
    id: 2,
    image: "http://cdn.motorpage.ru/Photos/300/1165B.jpg",
    text: "Some BMW",
    date: "2021-11-08",
    lessonNum: 50,
    title: "BMW",
    author: 124,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 3,
    image: "http://cdn.motorpage.ru/Photos/300/11066.jpg",
    text: "Some Audi",
    date: "2021-12-08",
    lessonNum: 51,
    title: "Audi",
    author: 125,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 4,
    image: "http://cdn.motorpage.ru/Photos/300/110E4.jpg",
    text: "Some Mercedes",
    date: "2021-10-15",
    lessonNum: 52,
    title: "Mercedes",
    author: 126,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 5,
    image: "http://cdn.motorpage.ru/Photos/300/11957.jpg",
    text: "Some Toyota",
    date: "2021-10-20",
    lessonNum: 53,
    title: "Toyota",
    author: 127,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 6,
    image: "http://cdn.motorpage.ru/Photos/300/1DB3.jpg",
    text: "Some Honda",
    date: "2021-11-01",
    lessonNum: 54,
    title: "Honda",
    author: 128,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 7,
    image: "http://cdn.motorpage.ru/Photos/300/19C.jpg",
    text: "Some Ford",
    date: "2021-10-28",
    lessonNum: 55,
    title: "Ford",
    author: 129,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 8,
    image: "http://cdn.motorpage.ru/Photos/300/Chevrolet_Bl.jpg",
    text: "Some Chevrolet",
    date: "2021-09-08",
    lessonNum: 56,
    title: "Chevrolet",
    author: 130,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 9,
    image: "http://cdn.motorpage.ru/Photos/300/1BC6.jpg",
    text: "Some Porsche",
    date: "2021-11-02",
    lessonNum: 57,
    title: "Porsche",
    author: 131,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 10,
    image: "http://cdn.motorpage.ru/Photos/300/1E54.jpg",
    text: "Some Lexus",
    date: "2021-10-22",
    lessonNum: 58,
    title: "Lexus",
    author: 132,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 11,
    image: "http://cdn.motorpage.ru/Photos/300/1B96.jpg",
    text: "Some Nissan",
    date: "2021-10-28",
    lessonNum: 59,
    title: "Nissan",
    author: 133,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 12,
    image: "http://cdn.motorpage.ru/Photos/300/1DCA.jpg",
    text: "Some Tesla",
    date: "2021-11-10",
    lessonNum: 60,
    title: "Tesla",
    author: 134,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 13,
    image: "http://cdn.motorpage.ru/Photos/300/1FD1.jpg",
    text: "Some Mazda",
    date: "2021-09-15",
    lessonNum: 61,
    title: "Mazda",
    author: 135,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 14,
    image: "http://cdn.motorpage.ru/Photos/300/Carens_1.jpg",
    text: "Some Kia",
    date: "2021-08-22",
    lessonNum: 62,
    title: "Kia",
    author: 136,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 15,
    image: "http://cdn.motorpage.ru/Photos/300/1D2.jpg",
    text: "Some Hyundai",
    date: "2021-11-15",
    lessonNum: 63,
    title: "Hyundai",
    author: 137,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 16,
    image: "http://cdn.motorpage.ru/Photos/300/1B4F.jpg",
    text: "Some Lamborghini",
    date: "2021-12-01",
    lessonNum: 64,
    title: "Lamborghini",
    author: 138,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 17,
    image: "http://cdn.motorpage.ru/Photos/300/Continental_B.jpg",
    text: "Some Bentley",
    date: "2021-11-12",
    lessonNum: 65,
    title: "Bentley",
    author: 139,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 18,
    image: "http://cdn.motorpage.ru/Photos/300/1E63.jpg",
    text: "Some Rolls Royce",
    date: "2021-11-22",
    lessonNum: 66,
    title: "Rolls Royce",
    author: 140,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 19,
    image: "http://cdn.motorpage.ru/Photos/300/1DA9.jpg",
    text: "Some Jaguar",
    date: "2021-12-10",
    lessonNum: 67,
    title: "Jaguar",
    author: 141,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 20,
    image: "http://cdn.motorpage.ru/Photos/300/11055.jpg",
    text: "Some Peugeot",
    date: "2021-11-28",
    lessonNum: 68,
    title: "Peugeot",
    author: 142,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 21,
    image: "http://cdn.motorpage.ru/Photos/800/4f8e6c5c17bf4.jpg",
    text: "Some Alfa Romeo",
    date: "2021-10-05",
    lessonNum: 69,
    title: "Alfa Romeo",
    author: 143,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 22,
    image: "http://cdn.motorpage.ru/Photos/300/Escudo_1.jpg",
    text: "Some Suzuki",
    date: "2021-09-25",
    lessonNum: 70,
    title: "Suzuki",
    author: 144,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 23,
    image: "http://cdn.motorpage.ru/Photos/300/111110.jpg",
    text: "Some Volvo",
    date: "2021-11-18",
    lessonNum: 71,
    title: "Volvo",
    author: 145,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 24,
    image: "http://cdn.motorpage.ru/Photos/300/17.jpg",
    text: "Some Bugatti",
    date: "2021-11-25",
    lessonNum: 72,
    title: "Bugatti",
    author: 146,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 25,
    image: "http://cdn.motorpage.ru/Photos/800/17D7.jpg",
    text: "Some Fiat",
    date: "2021-10-30",
    lessonNum: 73,
    title: "Fiat",
    author: 147,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 26,
    image: "http://cdn.motorpage.ru/Photos/300/4f8e6b8db1110.jpg",
    text: "Some Chrysler",
    date: "2021-10-12",
    lessonNum: 74,
    title: "Chrysler",
    author: 148,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 27,
    image: "http://cdn.motorpage.ru/Photos/300/1FFA.jpg",
    text: "Some Mitsubishi",
    date: "2021-12-05",
    lessonNum: 75,
    title: "Mitsubishi",
    author: 149,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 28,
    image: "http://cdn.motorpage.ru/Photos/300/11A2F.jpg",
    text: "Some Subaru",
    date: "2021-09-20",
    lessonNum: 76,
    title: "Subaru",
    author: 150,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 29,
    image: "http://cdn.motorpage.ru/Photos/300/11B7D.jpg",
    text: "Some Seat",
    date: "2021-10-26",
    lessonNum: 77,
    title: "Seat",
    author: 151,
    like: 0,
    dislike: 0,
    isFavorite: false,
  },
  {
    id: 30,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxW9ppg_BFCg2AY6pxJ6pU6tIU0qz3xY119g&s",
    text: "Some Dacia",
    date: "2021-11-05",
    lessonNum: 78,
    title: "Dacia",
    author: 152,
    like: 0,
    dislike: 0,
    isFavorite: false,
  }
  
];



export const getAllPosts = async (): Promise<IPost[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockPosts);
    }, 100);
  });
};

export const getPostById = async (id: number): Promise<IPost | null> => {
  return new Promise((resolve) => {
    const post = mockPosts.find(post => post.id === id) ?? null;

    setTimeout(() => {
      resolve(post);
    }, 0);
  });
};

